#ifndef __HERSHEY_GCODE_CONTROLLER_H__
#define __HERSHEY_GCODE_CONTROLLER_H__

#include "mcp_server.h"
#include "hershey_font_data.h"

#include <driver/uart.h>
#include <driver/gpio.h>
#include <esp_log.h>
#include <cstring>
#include <string>
#include <cmath>

#define ENGRAVING_AREA_WIDTH  42.0f
#define ENGRAVING_AREA_HEIGHT 42.0f

// ─── HersheyGcodeController 类 ─────────────────────────────

class HersheyGcodeController {
private:
    static constexpr uart_port_t UART_PORT  = UART_NUM_2;
    static constexpr gpio_num_t UART_TX_PIN = GPIO_NUM_20;
    static constexpr gpio_num_t UART_RX_PIN = GPIO_NUM_19;
    static constexpr int UART_BAUD = 115200;
    static constexpr float DEFAULT_SIZE = 5.0f;
    static constexpr int DEFAULT_POWER = 800;
    static constexpr int DEFAULT_FEED_RATE = 800;

    // 查找字符的笔画数据，找不到返回 nullptr
    static const int8_t* LookupChar(char ch, uint8_t& out_width) {
        int count;
        const HersheyChar* table = hershey_lookup_table(count);
        for (int i = 0; i < count; i++) {
            if (table[i].code == ch) {
                out_width = table[i].width;
                return table[i].strokes;
            }
        }
        out_width = 0;
        return nullptr;
    }

    // 生成单个字符的 G-code
    static void GenerateCharGcode(std::string& gcode, char ch,
                                  float& x_cursor, float y_base,
                                  float scale, int power, int feed_rate) {
        uint8_t char_width;
        const int8_t* data = LookupChar(ch, char_width);

        if (data == nullptr || char_width == 0) {
            x_cursor += 8.0f * scale;
            return;
        }

        // 扫描字符数据, 找到 min_x / max_y 用于归一化到正数坐标
        // 注意: Hershey 坐标系 Y+ 向下, G-code Y+ 向上, 需要翻转 Y 轴
        int8_t min_x = 0, max_y = -128;
        {
            const int8_t* scan = data;
            while (*scan != HERSHEY_STROKE_END) {
                int8_t n = *scan++;
                for (int i = 0; i < n; i++) {
                    int8_t sx = scan[i * 2];
                    int8_t sy = scan[i * 2 + 1];
                    if (sx < min_x) min_x = sx;
                    if (sy > max_y) max_y = sy;
                }
                scan += n * 2;
            }
        }

        char buf[128];
        float x_offset = x_cursor - min_x * scale;
        float y_offset = y_base   + max_y * scale;  // Y翻转后, max_y 对应视觉底部

        while (*data != HERSHEY_STROKE_END) {
            int8_t n_vertices = *data++;

            for (int i = 0; i < n_vertices; i++) {
                float gx = x_offset + static_cast<float>(data[i * 2]) * scale;
                float gy = y_offset - static_cast<float>(data[i * 2 + 1]) * scale;  // 翻转 Y

                if (i == 0) {
                    int len = snprintf(buf, sizeof(buf),
                        "G0 X%.3f Y%.3f\n", gx, gy);
                    gcode.append(buf, len);
                    len = snprintf(buf, sizeof(buf),
                        "M3 S%d\n", power);
                    gcode.append(buf, len);
                } else {
                    int len = snprintf(buf, sizeof(buf),
                        "G1 X%.3f Y%.3f F%d\n", gx, gy, feed_rate);
                    gcode.append(buf, len);
                }
            }

            gcode.append("M5\n");
            data += n_vertices * 2;
        }

        x_cursor += char_width * scale;
    }

    // 生成完整 G-code
    static std::string GenerateGcode(const std::string& text,
                                     float size_mm, float x_start, float y_start,
                                     int power, int feed_rate) {
        std::string gcode;
        char buf[128];

        // Header
        gcode.append("; Laser Engraving G-code\n");
        gcode.append("; Generated by xiaozhi-esp32\n");
        int len = snprintf(buf, sizeof(buf),
            "; Text: \"%s\"  Size: %.1fmm  Power: %d\n",
            text.c_str(), size_mm, power);
        gcode.append(buf, len);
        gcode.append("G21 ; mm\n");
        gcode.append("G90 ; absolute\n");

        // 范围校验
        float scale = size_mm / HERSHEY_FONT_HEIGHT;

        // 预估总宽度
        float total_width = 0.0f;
        for (char ch : text) {
            uint8_t w;
            const int8_t* d = LookupChar(ch, w);
            total_width += (d && w > 0) ? w * scale : 8.0f * scale;
        }
        float total_height = size_mm;

        if (x_start + total_width > ENGRAVING_AREA_WIDTH ||
            y_start + total_height > ENGRAVING_AREA_HEIGHT) {
            int len2 = snprintf(buf, sizeof(buf),
                "{\"error\":\"超出雕刻范围(42x42mm): 文字宽%.1fmm,高%.1fmm,起点(%.0f,%.0f)\"}",
                total_width, total_height, x_start, y_start);
            return std::string(buf, len2);
        }

        // 逐个字符生成 G-code
        float x_cursor = x_start;
        for (char ch : text) {
            len = snprintf(buf, sizeof(buf), "; Char: %c\n", ch);
            gcode.append(buf, len);
            GenerateCharGcode(gcode, ch, x_cursor, y_start,
                            scale, power, feed_rate);
        }

        // 回原点
        gcode.append("G0 X0 Y0\n");
        gcode.append("; End\n");

        return gcode;
    }

public:
    HersheyGcodeController() {
        // 初始化 UART2
        uart_config_t uart_config = {
            .baud_rate = UART_BAUD,
            .data_bits = UART_DATA_8_BITS,
            .parity    = UART_PARITY_DISABLE,
            .stop_bits = UART_STOP_BITS_1,
            .flow_ctrl = UART_HW_FLOWCTRL_DISABLE,
        };
        ESP_ERROR_CHECK(uart_driver_install(UART_PORT, 2048, 0, 0, NULL, 0));
        ESP_ERROR_CHECK(uart_param_config(UART_PORT, &uart_config));
        ESP_ERROR_CHECK(uart_set_pin(UART_PORT, UART_TX_PIN, UART_RX_PIN,
                                      UART_PIN_NO_CHANGE, UART_PIN_NO_CHANGE));
        ESP_LOGI("HersheyGcode", "UART2 initialized: TX=IO%d, RX=IO%d, baud=%d",
                 UART_TX_PIN, UART_RX_PIN, UART_BAUD);
    }

    void Initialize(McpServer& mcp_server) {
        mcp_server.AddTool("self.engraving.engrave_text",
            "生成激光雕刻 G-code 并发送给激光雕刻机。当用户要求雕刻/刻字时调用此工具。\n"
            "仅支持 ASCII: A-Z, a-z, 0-9, ! \" # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \\ ] _ { | } ~。"
            "不支持中文。\n"
            "用户口述符号时, 务必在 `text` 中转为实际字符:\n"
            "  \"at\"\"艾特\"→@  \"美元\"→$  \"井号\"→#  \"百分号\"→%  \"和\"\"and\"→&  \"星号\"→*\n"
            "  \"加号\"→+  \"减号\"\"横线\"→-  \"点\"\"句号\"→.  \"斜杠\"→/  \"冒号\"→:  \"问号\"→?\n"
            "  \"感叹号\"→!  \"左括号\"→(  \"右括号\"→)  \"小于\"→<  \"大于\"→>  \"等于\"→=\n"
            "  \"单引号\"→'  \"双引号\"→\"  \"逗号\"→,  \"分号\"→;\n"
            "  \"下划线\"→_  \"竖线\"→|  \"波浪号\"→~  \"方括号\"→[ ]  \"花括号\"→{ }  \"反斜杠\"→\\\n"
            "参数:\n"
            "  `text` 要雕刻的文字   `size` 字高mm(1-42)默认5   `power` 激光功率0-1000默认800\n"
            "  `feed_rate` 速度mm/min默认800   `x` `y` 起始位置mm默认(0,0)\n"
            "雕刻范围 42x42mm, 超出则返回错误。",
            PropertyList({
                Property("text", kPropertyTypeString),
                Property("size", kPropertyTypeInteger, 5, 1, 42),
                Property("power", kPropertyTypeInteger, 800, 0, 1000),
                Property("feed_rate", kPropertyTypeInteger, 800, 100, 5000),
                Property("x", kPropertyTypeInteger, 0, 0, 40),
                Property("y", kPropertyTypeInteger, 0, 0, 40),
            }),
            [this](const PropertyList& properties) -> ReturnValue {
                std::string text = properties["text"].value<std::string>();
                float size_mm     = static_cast<float>(properties["size"].value<int>());
                int power         = properties["power"].value<int>();
                int feed_rate     = properties["feed_rate"].value<int>();
                float x_start     = static_cast<float>(properties["x"].value<int>());
                float y_start     = static_cast<float>(properties["y"].value<int>());

                // 参数校验
                if (text.empty()) {
                    throw std::runtime_error("text 不能为空");
                }
                if (x_start >= ENGRAVING_AREA_WIDTH) {
                    throw std::runtime_error("起始 X 坐标超出雕刻范围(0~42mm)");
                }
                if (y_start >= ENGRAVING_AREA_HEIGHT) {
                    throw std::runtime_error("起始 Y 坐标超出雕刻范围(0~42mm)");
                }

                // 生成 G-code
                std::string gcode = GenerateGcode(text, size_mm,
                                                  x_start, y_start,
                                                  power, feed_rate);

                // 如果以 { 开头表示 JSON 错误
                if (!gcode.empty() && gcode[0] == '{') {
                    throw std::runtime_error(gcode);
                }

                // 通过 UART2 发送
                int sent = uart_write_bytes(UART_PORT, gcode.c_str(),
                                            gcode.size());
                ESP_LOGI("HersheyGcode", "Sent %d/%d bytes via UART2",
                         sent, gcode.size());

                // 统计行数
                int line_count = 0;
                for (char c : gcode) {
                    if (c == '\n') line_count++;
                }

                cJSON* result = cJSON_CreateObject();
                cJSON_AddStringToObject(result, "text", text.c_str());
                cJSON_AddNumberToObject(result, "size_mm", size_mm);
                cJSON_AddNumberToObject(result, "power", power);
                cJSON_AddNumberToObject(result, "feed_rate", feed_rate);
                cJSON_AddNumberToObject(result, "x", x_start);
                cJSON_AddNumberToObject(result, "y", y_start);
                cJSON_AddNumberToObject(result, "lines", line_count);
                cJSON_AddStringToObject(result, "gcode", gcode.c_str());
                cJSON_AddStringToObject(result, "sent_to", "UART2");

                return result;
            });
    }
};

#endif // __HERSHEY_GCODE_CONTROLLER_H__
